import { notFound } from "next/navigation";
import { one } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { serialize } from "@/lib/genedit";
import { approveGeneration, createInsightDraft, createProductDraft, saveGenerationEdits } from "../../../../ai-actions";
import { Badge, PageHeader, Panel } from "@/components/admin/ui";

export const metadata = { title: "Review generation" };
type G = { id: string; kind: string; status: string; model: string | null; input: Record<string, string>; output: Record<string, unknown>; product_id: string | null };

export default async function Generation({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> }) {
  const user = await requireUser();
  const { id } = await params; const { error } = await searchParams;
  if (!/^[0-9a-f-]{36}$/.test(id)) notFound();
  const g = await one<G>("SELECT id,kind,status,model,input,output,product_id FROM ai_generations WHERE id=$1", [id]);
  if (!g || !["product_marketing", "content_factory"].includes(g.kind)) notFound();
  const isProduct = g.kind === "product_marketing";
  return (
    <>
      <PageHeader title={isProduct ? `Product marketing: ${g.input.name}` : `Content: ${g.input.topic?.slice(0, 80)}`} sub={`Generated by ${g.model ?? "AI"} — AI output can contain errors. Verify every claim before use. Workflow: generate → preview → edit → approve → create draft → publish.`}
        actions={<Badge tone={g.status === "approved" ? "green" : "amber"}>{g.status}</Badge>} />
      {error && <p role="alert" className="mb-4 rounded-lg border border-rose-500/40 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</p>}
      <form action={saveGenerationEdits} className="space-y-4">
        <input type="hidden" name="id" value={g.id} />
        {Object.entries(g.output).map(([k, v]) => (
          <Panel key={k} title={k.replace(/_/g, " ")}>
            <label className="sr-only" htmlFor={`f_${k}`}>{k}</label>
            <textarea id={`f_${k}`} name={`f_${k}`} rows={Math.min(24, Math.max(3, serialize(v).split("\n").length + 1))} defaultValue={serialize(v)} className="field font-mono text-xs" />
          </Panel>
        ))}
        <button className="btn-ghost">Save edits (returns to draft)</button>
      </form>
      <Panel title="Approval & next step" className="mt-5">
        <div className="flex flex-wrap items-center gap-3">
          {g.status === "draft" && user.role === "admin" && <form action={approveGeneration}><input type="hidden" name="id" value={g.id} /><button className="btn-primary !py-2">Approve</button></form>}
          {g.status === "draft" && user.role !== "admin" && <p className="text-sm text-slate-400">An administrator must approve this before a draft can be created.</p>}
          {g.status === "approved" && (isProduct
            ? (g.product_id ? <p className="text-sm text-emerald-400">Product draft already created.</p> : <form action={createProductDraft}><input type="hidden" name="id" value={g.id} /><button className="btn-primary !py-2">Create product draft</button></form>)
            : <form action={createInsightDraft}><input type="hidden" name="id" value={g.id} /><button className="btn-primary !py-2">Create article draft</button></form>)}
          <p className="text-xs text-slate-500">Drafts still go through review → approval → publish. Social, email and ad copy are not sent or launched from here.</p>
        </div>
      </Panel>
    </>
  );
}
